### PR TITLE
Fixed the bugs with incorrect data appearing for the clusters.

### LINKED ISSUE #269: Fix map filter bugs
Noticed a couple of bugs when using the Arbovirus checkboxes to filter the map
- Screenshot 1: Only Zika and Dengue selected but the # of estimates clustered show other viruses 
- Screenshot 2: ESM Dengue 2015 selected and map looks good - then ELISA filter applied and # of estimates clustered show other viruses

In both these cases when you zoom in on the clusters, it displays the correct data

Image

Image

### PR DESCRIPTION
**Pull request by SeanKennyNF**
Resolves #269. The map flickers a little bit when the filters change even if the cluster hasn't changed it's data. I think the intent of the original caching code (which was causing this problem) was to remove the flicker and to save generating elements we don't have to. This saves generating elements we don't have to but still has problems with flickering. Production also has problems with flickering, I think we should do something more in-depth to remove that flickering but I'm just fixing the bug for now.

Peek 2024-05-27 18-24

### CODE REVIEW

File: app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx [hunk 1]
```diff
@@ -217,22 +241,37 @@ export function computeClusterMarkers(props: {
...
+        else {
+          const marker = createClusterPointMarker({
+            element: element,
             coords: [coords[0], coords[1]],
             id: id,
             map: props.map,
           });
-        }
-        if (marker) {
-          newMarkers[id] = marker;
```
Comment (SeanKennyNF) [inline app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx:235]: The culprit

Comment (HimanshuRanka) [reply app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx:235]: wait tell me more

**Review by HimanshuRanka — APPROVED** [review]
